export const PET_PHRASES: string[] = [
  '🌿 Cố lên nhé!',
  '📚 Hôm nay đọc sách chưa?',
  '☕ Nghỉ chút rồi học tiếp.',
  '😄 Bạn làm tốt lắm!',
  '💪 Cùng nhau tiến bộ nào.',
  '🌟 Bạn là ngôi sao sáng!',
  '🎯 Tập trung vào mục tiêu nhé.',
  '🧠 Kiến thức là sức mạnh.',
  '🌱 Mỗi ngày một chút, cây sẽ lớn.',
  '🐾 Mình thích học cùng bạn.',
  '✨ Hôm nay bạn thật rực rỡ.',
  '📝 Nhớ ghi chú lại nhé.',
  '🍀 Chúc bạn may mắn.',
  '🎉 Hoàn thành rồi! Ăn mừng thôi.',
  '🌈 Sau cơn mưa trời lại sáng.',
  '✨ Mỗi ngày là một món quà.',
'🌈 Sau cơn mưa trời lại sáng.',
'☀️ Hãy tỏa sáng theo cách của bạn.',
'🌸 Vạn sự khởi đầu nan.',
'💪 Bạn làm được mà!',
'🦋 Thay đổi để tốt hơn.',
'🌿 Cứ đi rồi sẽ đến.',
'🎈 Luôn mỉm cười nhé.',
'🌊 Thuận theo tự nhiên.',
'🌙 Mọi chuyện rồi sẽ ổn.',
'🍀 May mắn luôn bên bạn.',
'🔥 Đừng bao giờ bỏ cuộc.',
'🍓 Yêu đời mỗi ngày.',
'🍃 Bình yên trong tâm hồn.',
'🚀 Ước mơ không có giới hạn.',
'🍯 Ngọt ngào như yêu thương.',
'🌻 Hướng về phía mặt trời.',
'💎 Bạn là phiên bản duy nhất.',
'🌈 Vẽ nên cầu vồng của bạn.',
'💡 Ý tưởng mới bắt đầu.',
'🌟 Hãy là ngôi sao sáng.',
'🎁 Trân trọng từng khoảnh khắc.',
'💌 Gửi một cái ôm ấm áp.',
'🌊 Vững vàng trước sóng gió.',
'🎶 Cuộc sống là bản nhạc hay.',
'🌈 Sống trọn vẹn từng giây.',
'🍃 Hít thở sâu và thư giãn.',
'🐾 Bước từng bước nhỏ thôi.',
'🌞 Nụ cười là liều thuốc.',
'💖 Yêu thương chính mình.',
'🏅 Bạn giỏi hơn bạn nghĩ.',
'🎨 Tô màu cho cuộc sống.',
'⚓ Giữ vững niềm tin.',
'🕊️ Bình yên trong hiện tại.',
'⭐ Ánh sáng trong bạn.',
'🌦️ Mạnh mẽ sau bão giông.',
'🍭 Ngọt ngào chờ đón bạn.',
'💫 Mọi điều đều có thể.',
'🧠 Học hỏi mỗi ngày.',
'🌼 Nở hoa trong nghịch cảnh.',
'🔋 Nạp lại năng lượng thôi.',
'🌊 Sóng sẽ mang đến điều mới.',
'🌤️ Ngày mai sẽ tươi đẹp.',
'🗝️ Bạn nắm giữ chìa khóa.',
'🌈 Luôn tin vào điều tốt đẹp.',
'🕊️ Tự do là chính mình.',
'🔥 Nhiệt huyết vẫn cháy mãi.',
'🍀 Bình an trong tâm trí.',
'💎 Tỏa sáng như kim cương.',
'🌻 Năng lượng tích cực nhé.',
'🎈 Bay lên với ước mơ.',
'🌿 Chăm sóc tâm hồn bạn.',
'🌟 Mọi thứ sẽ tốt đẹp hơn.',
'🌅 Một khởi đầu mới.',
'🌸 Vẻ đẹp nằm ở nỗ lực.',
'💪 Bản lĩnh tạo thành công.',
'🌈 Màu sắc của hy vọng.',
'⚡ Bạn đầy sức mạnh.',
'🍃 An nhiên mà sống.',
'🐾 Cứ tiến về phía trước.',
'🌞 Chào ngày mới rạng rỡ.',
'💖 Lan tỏa yêu thương.',
'🏅 Hãy là người chiến thắng.',
'🚀 Vươn tới những vì sao.',
'🍃 Gác lại mọi ưu phiền.',
'🌈 Hy vọng luôn ở đó.',
'💡 Suy nghĩ tích cực lên.',
'🌟 Tỏa sáng theo cách riêng.',
'🌸 Hương sắc của cuộc đời.',
'🔥 Quyết tâm không lùi bước.',
'🍀 May mắn đang chờ bạn.',
'🌊 Dòng đời luôn chảy trôi.',
'🌞 Hãy sống thật rực rỡ.',
'🎈 Niềm vui nhỏ mỗi ngày.',
'💎 Trân trọng giá trị bản thân.',
'🌈 Chân trời phía trước.',
'🕊️ Thanh thản trong tâm hồn.',
'🌻 Mạnh mẽ và tự tin.',
'🐾 Đừng quên mục tiêu.',
'🌞 Nắng lên cho tâm hồn.',
'💖 Trao đi thật nhiều yêu.',
'🏅 Thành công đang đợi bạn.',
'🚀 Chinh phục mọi đỉnh cao.',
'🍃 Sống chậm lại một chút.',
'🌈 Kết nối những niềm vui.',
'💡 Sáng tạo không ngừng.',
'🌟 Bạn là niềm tự hào.',
'🌸 Nở rộ giữa đời thường.',
'🔥 Cháy hết mình với đam mê.',
'🍀 Hạnh phúc ở ngay đây.',
'🌊 Sóng yên biển lặng.',
'🌞 Năng lượng tràn đầy.',
'🎈 Vui vẻ đón ngày mới.',
'💎 Giữ vững lòng kiên định.',
'🌈 Rực rỡ như cầu vồng.',
'🕊️ Tâm hồn thật tự do.',
'🌻 Luôn giữ nụ cười trên môi.',
'🐾 Bước đi thật vững vàng.',
'🌞 Một ngày thật tuyệt vời.',
'💖 Yêu thương ngập tràn.'
];